import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NaviBar from "@/components/NaviBar";
import { Suspense } from 'react';
import Loading from "@/app/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Compare",
  description: "Generated by Jack the Coder",
  authors: [
    { name: "JackTheCoder", url: "https://jackthecoder.dev/" },
    { name: "KubaKoder", url: "https://kubakoder.pl/" }
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-w-full min-h-screen	">
          <NaviBar />
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </div>
      </body>
    </html>
  );
}
