import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NaviBar from "@/components/NaviBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-w-full min-h-screen	">
          <NaviBar />
          {children}
        </div>
      </body>
    </html>
  );
}
